#!/usr/bin/env node
/**
 * Build script: copies `src/` to `dist/` (preserving structure) and inlines
 * the `webextension-polyfill` so the loaded extension does not require a
 * bundler at runtime.
 *
 * Strategy (Task 9.2):
 *   1. Recursively copy `src/` to `dist/`. Because the polyfill is vendored
 *      at `src/vendor/browser-polyfill.min.js`, it lands at
 *      `dist/vendor/browser-polyfill.min.js` automatically.
 *   2. If the source-vendored copy is missing for any reason, fall back to
 *      copying the polyfill from `node_modules/webextension-polyfill/` so
 *      the build still produces a valid loadable extension.
 *   3. Rewrite `dist/shared/browser.js` so the loaded extension reaches the
 *      vendored polyfill via a relative path instead of a bare specifier
 *      (`'webextension-polyfill'`). The source file keeps the bare specifier
 *      so Node-based tooling (Vitest, ESLint) can still resolve the
 *      package; the rewrite only happens in the produced `dist/`.
 *   4. Verify that no `from 'webextension-polyfill'` bare specifier remains
 *      anywhere under `dist/`. If one is found, the build fails — this
 *      protects future modules from accidentally bypassing the seam.
 */

import { existsSync } from 'node:fs';
import {
    cp,
    mkdir,
    readdir,
    readFile,
    rm,
    stat,
    writeFile
} from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const srcDir = resolve(root, 'src');
const distDir = resolve(root, 'dist');
const polyfillNodeModules = resolve(
    root,
    'node_modules/webextension-polyfill/dist/browser-polyfill.min.js'
);
const polyfillVendoredInDist = resolve(
    distDir,
    'vendor/browser-polyfill.min.js'
);
const distBrowserShim = resolve(distDir, 'shared/browser.js');

// The shim that ships in `dist/shared/browser.js`. It performs a side-effect
// ES-module import of the vendored polyfill (whose UMD wrapper installs
// `globalThis.browser` when no AMD/CommonJS environment is present) and then
// re-exports the freshly-installed global. The relative path is correct
// from `dist/shared/browser.js` to `dist/vendor/browser-polyfill.min.js`.
const DIST_BROWSER_SHIM = `// Generated by scripts/build.js — do not edit by hand.
//
// Loads the vendored webextension-polyfill (UMD) for its side effect of
// installing the promise-based \`browser\` API on \`globalThis\`, then
// re-exports it. Calling modules import \`browser\` from this single seam
// so the extension never references \`chrome.*\` directly.

import '../vendor/browser-polyfill.min.js';

const browser = globalThis.browser;

export { browser };
export default browser;
`;

async function walk(dir) {
    const out = [];
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
        const full = join(dir, entry.name);
        if (entry.isDirectory()) {
            out.push(...(await walk(full)));
        } else if (entry.isFile()) {
            out.push(full);
        }
    }
    return out;
}

async function ensurePolyfillVendored() {
    if (existsSync(polyfillVendoredInDist)) {
        return;
    }
    if (!existsSync(polyfillNodeModules)) {
        throw new Error(
            `[build] webextension-polyfill not found at ${polyfillNodeModules} ` +
            `and no source-vendored copy at src/vendor/. Run \`npm install\` ` +
            `or vendor the polyfill into src/vendor/browser-polyfill.min.js.`
        );
    }
    await mkdir(dirname(polyfillVendoredInDist), { recursive: true });
    await cp(polyfillNodeModules, polyfillVendoredInDist);
    console.log(
        `[build] Source-vendored polyfill missing; copied from node_modules -> dist/vendor/`
    );
}

async function rewriteBrowserShim() {
    if (!existsSync(distBrowserShim)) {
        throw new Error(
            `[build] expected dist/shared/browser.js to exist after copying src/`
        );
    }
    await writeFile(distBrowserShim, DIST_BROWSER_SHIM, 'utf8');
    console.log(
        `[build] Rewrote dist/shared/browser.js to use the vendored polyfill`
    );
}

async function assertNoBareSpecifierInDist() {
    const files = await walk(distDir);
    const offenders = [];
    // Match either single- or double-quoted bare specifier imports/requires
    // of webextension-polyfill anywhere in any text file under dist/.
    const bareSpecifier = /['"]webextension-polyfill['"]/;
    for (const file of files) {
        // Skip the vendored polyfill bundle itself (it contains a self
        // identification string and a UMD `define("webextension-polyfill", …)`
        // call that is not a module import).
        if (file === polyfillVendoredInDist) continue;
        const info = await stat(file);
        if (info.size > 5 * 1024 * 1024) continue;
        // Only inspect text-like extensions to avoid binary blobs (icons).
        if (!/\.(?:js|mjs|cjs|html|json|css|map)$/i.test(file)) continue;
        const text = await readFile(file, 'utf8');
        if (bareSpecifier.test(text)) {
            offenders.push(relative(distDir, file));
        }
    }
    if (offenders.length > 0) {
        throw new Error(
            `[build] Bare specifier 'webextension-polyfill' still present in ` +
            `dist/ files: ${offenders.join(', ')}. The build must rewrite ` +
            `every import to the vendored relative path.`
        );
    }
}

async function main() {
    if (!existsSync(srcDir)) {
        console.warn(
            `[build] src/ directory not found at ${srcDir}; nothing to copy.`
        );
        await mkdir(distDir, { recursive: true });
        return;
    }

    await rm(distDir, { recursive: true, force: true });
    await mkdir(distDir, { recursive: true });
    await cp(srcDir, distDir, { recursive: true });
    console.log(`[build] Copied src/ -> dist/`);

    await ensurePolyfillVendored();
    await rewriteBrowserShim();
    await assertNoBareSpecifierInDist();

    console.log(`[build] Built dist/ is self-contained.`);
}

main().catch((err) => {
    console.error(`[build] Failed:`, err);
    process.exit(1);
});
