#!/usr/bin/env node
/**
 * Build script: produces per-browser, self-contained extension packages
 * under `dist/chrome/` and `dist/firefox/` from the cross-browser source
 * tree under `src/`.
 *
 * `src/manifest.json` is a "union" manifest that declares both the
 * Chrome MV3 background entry (`service_worker`) and the Firefox <121
 * MV3 background entry (`scripts`). Chrome MV3 rejects manifests that
 * still contain `background.scripts` (error: "requires manifest version
 * of 2 or lower"), so the manifest must be split per browser at build
 * time.
 *
 * Strategy:
 *   1. For each variant (chrome, firefox), recursively copy `src/` to
 *      `dist/<variant>/`. Because the polyfill is vendored at
 *      `src/vendor/browser-polyfill.min.js`, it lands at
 *      `dist/<variant>/vendor/browser-polyfill.min.js` automatically.
 *   2. If the source-vendored copy is missing, fall back to copying
 *      the polyfill from `node_modules/webextension-polyfill/`.
 *   3. Rewrite `dist/<variant>/shared/browser.js` so the loaded
 *      extension reaches the vendored polyfill via a relative path
 *      instead of a bare specifier (`'webextension-polyfill'`). The
 *      source file keeps the bare specifier so Node-based tooling
 *      (Vitest, ESLint) can still resolve the package; the rewrite
 *      only happens in the produced `dist/`.
 *   4. Rewrite `dist/<variant>/manifest.json` to keep only the keys
 *      that browser accepts.
 *   5. Verify that no `from 'webextension-polyfill'` bare specifier
 *      remains anywhere under either variant directory.
 */

import { existsSync } from 'node:fs';
import {
    cp,
    mkdir,
    readdir,
    readFile,
    rm,
    stat,
    writeFile
} from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const srcDir = resolve(root, 'src');
const distRoot = resolve(root, 'dist');
const polyfillNodeModules = resolve(
    root,
    'node_modules/webextension-polyfill/dist/browser-polyfill.min.js'
);

// The shim that ships in `dist/<variant>/shared/browser.js`. It performs a
// side-effect ES-module import of the vendored polyfill (whose UMD wrapper
// installs `globalThis.browser` when no AMD/CommonJS environment is
// present) and then re-exports the freshly-installed global. The relative
// path is correct from `shared/browser.js` to `vendor/browser-polyfill.min.js`.
const DIST_BROWSER_SHIM = `// Generated by scripts/build.js — do not edit by hand.
//
// Loads the vendored webextension-polyfill (UMD) for its side effect of
// installing the promise-based \`browser\` API on \`globalThis\`, then
// re-exports it. Calling modules import \`browser\` from this single seam
// so the extension never references \`chrome.*\` directly.

import '../vendor/browser-polyfill.min.js';

const browser = globalThis.browser;

export { browser };
export default browser;
`;

/**
 * Per-browser manifest transforms. Each receives a freshly-parsed copy of
 * the union manifest and returns the variant-specific manifest object.
 */
const VARIANTS = [
    {
        name: 'chrome',
        transformManifest(manifest) {
            const out = structuredClone(manifest);
            // Chrome MV3 only accepts `service_worker`. Leaving `scripts`
            // in place produces "background.scripts requires manifest
            // version of 2 or lower" and aborts service-worker registration.
            if (out.background) {
                delete out.background.scripts;
            }
            // `browser_specific_settings` is Firefox-only and Chrome
            // ignores it, but stripping it keeps the file minimal.
            delete out.browser_specific_settings;
            return out;
        }
    },
    {
        name: 'firefox',
        transformManifest(manifest) {
            const out = structuredClone(manifest);
            // Firefox MV3 uses an event page (`background.scripts`) and
            // does not support `background.service_worker`, so strip the
            // Chrome-style service_worker entry for the Firefox build.
            // (strict_min_version is 140; even current Firefox has no
            // background service worker.)
            if (out.background) {
                delete out.background.service_worker;
            }
            // Chrome-only key.
            delete out.minimum_chrome_version;
            return out;
        }
    }
];

async function walk(dir) {
    const out = [];
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
        const full = join(dir, entry.name);
        if (entry.isDirectory()) {
            out.push(...(await walk(full)));
        } else if (entry.isFile()) {
            out.push(full);
        }
    }
    return out;
}

async function ensurePolyfillVendored(variantDir) {
    const polyfillVendoredInDist = resolve(
        variantDir,
        'vendor/browser-polyfill.min.js'
    );
    if (existsSync(polyfillVendoredInDist)) {
        return polyfillVendoredInDist;
    }
    if (!existsSync(polyfillNodeModules)) {
        throw new Error(
            `[build] webextension-polyfill not found at ${polyfillNodeModules} ` +
            `and no source-vendored copy at src/vendor/. Run \`npm install\` ` +
            `or vendor the polyfill into src/vendor/browser-polyfill.min.js.`
        );
    }
    await mkdir(dirname(polyfillVendoredInDist), { recursive: true });
    await cp(polyfillNodeModules, polyfillVendoredInDist);
    console.log(
        `[build] Source-vendored polyfill missing; copied from node_modules -> ${relative(
            root,
            polyfillVendoredInDist
        )}`
    );
    return polyfillVendoredInDist;
}

async function rewriteBrowserShim(variantDir) {
    const distBrowserShim = resolve(variantDir, 'shared/browser.js');
    if (!existsSync(distBrowserShim)) {
        throw new Error(
            `[build] expected ${relative(root, distBrowserShim)} to exist after copying src/`
        );
    }
    await writeFile(distBrowserShim, DIST_BROWSER_SHIM, 'utf8');
    console.log(
        `[build] Rewrote ${relative(root, distBrowserShim)} to use the vendored polyfill`
    );
}

async function writeManifest(variantDir, sourceManifest, variant) {
    const transformed = variant.transformManifest(sourceManifest);
    const target = resolve(variantDir, 'manifest.json');
    await writeFile(target, JSON.stringify(transformed, null, 4) + '\n', 'utf8');
    console.log(
        `[build] Wrote ${relative(root, target)} for ${variant.name}`
    );
}

async function assertNoBareSpecifierInDist(variantDir, polyfillVendored) {
    const files = await walk(variantDir);
    const offenders = [];
    // Match either single- or double-quoted bare specifier imports/requires
    // of webextension-polyfill anywhere in any text file under the variant.
    const bareSpecifier = /['"]webextension-polyfill['"]/;
    for (const file of files) {
        // Skip the vendored polyfill bundle itself (it contains a self
        // identification string and a UMD `define("webextension-polyfill", …)`
        // call that is not a module import).
        if (file === polyfillVendored) continue;
        const info = await stat(file);
        if (info.size > 5 * 1024 * 1024) continue;
        // Only inspect text-like extensions to avoid binary blobs (icons).
        if (!/\.(?:js|mjs|cjs|html|json|css|map)$/i.test(file)) continue;
        const text = await readFile(file, 'utf8');
        if (bareSpecifier.test(text)) {
            offenders.push(relative(variantDir, file));
        }
    }
    if (offenders.length > 0) {
        throw new Error(
            `[build] Bare specifier 'webextension-polyfill' still present in ` +
            `${relative(root, variantDir)} files: ${offenders.join(', ')}. ` +
            `The build must rewrite every import to the vendored relative path.`
        );
    }
}

async function buildVariant(sourceManifest, variant) {
    const variantDir = resolve(distRoot, variant.name);
    await mkdir(variantDir, { recursive: true });
    await cp(srcDir, variantDir, { recursive: true });
    console.log(`[build] Copied src/ -> ${relative(root, variantDir)}`);

    const polyfillVendored = await ensurePolyfillVendored(variantDir);
    await rewriteBrowserShim(variantDir);
    await writeManifest(variantDir, sourceManifest, variant);
    await assertNoBareSpecifierInDist(variantDir, polyfillVendored);
    console.log(
        `[build] ${variant.name} build at ${relative(root, variantDir)} is self-contained.`
    );
}

async function main() {
    if (!existsSync(srcDir)) {
        console.warn(
            `[build] src/ directory not found at ${srcDir}; nothing to copy.`
        );
        await mkdir(distRoot, { recursive: true });
        return;
    }

    await rm(distRoot, { recursive: true, force: true });
    await mkdir(distRoot, { recursive: true });

    const sourceManifestPath = resolve(srcDir, 'manifest.json');
    const sourceManifest = JSON.parse(
        await readFile(sourceManifestPath, 'utf8')
    );

    for (const variant of VARIANTS) {
        await buildVariant(sourceManifest, variant);
    }
}

main().catch((err) => {
    console.error(`[build] Failed:`, err);
    process.exit(1);
});
